# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["VAGRANT_EXPERIMENTAL"] = "disks"

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/8.4'
  config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'
  config.vm.box_download_checksum = 'dfe4a34e59eb3056a6fe67625454c3607cbc52ae941aeba0498c29ee7cb9ac22'
  config.vm.box_download_checksum_type = 'sha256'

config.vm.define "server" do |server|

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end


  server.vm.disk :disk, size: "1GB", name: "disk1"
  server.vm.disk :disk, size: "1GB", name: "disk2"
  server.vm.disk :disk, size: "1GB", name: "disk3"

  config.vm.provider "virtualbox" do |vb|
    needsController = false
    if not  File.exist?('disk01.vdi')
      vb.customize ['createhd', '--filename', 'disk01.vdi','--variant', 'Fixed', '--size', 2048]
      vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', 'disk01.vdi'] 
    end
    if not  File.exist?('disk02.vdi')
      vb.customize ['createhd', '--filename', 'disk02.vdi','--variant', 'Fixed', '--size', 2048]
      vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 1, '--type', 'hdd', '--medium', 'disk02.vdi']
    end
    if not  File.exist?('disk03.vdi')
      vb.customize ['createhd', '--filename', 'disk03.vdi','--variant', 'Fixed', '--size', 2048]
      vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'disk03.vdi']
    end

  end
 # server.vm.disk :disk, size: "1GB", name: "disk1"
 # server.vm.disk :disk, size: "1GB", name: "disk2"
 # server.vm.disk :disk, size: "1GB", name: "disk3"
  #server.vm.disk :disk, size: "1GB", name: "disk4"
  #server.vm.disk :disk, size: "1GB", name: "disk5"
  #server.vm.disk :disk, size: "1GB", name: "disk6"
  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.0.41"



  server.vm.provision "shell",
    name: "Setup zfs",
    path: "setup_zfs.sh"
  end


# Cent OS 8.2
# config used from this
# https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
  config.vm.define "client" do |client|
    client.vm.host_name = 'client'
    client.vm.network :private_network, ip: "10.0.0.40"
    client.vm.disk :disk, size: "1GB", name: "disk1"
    client.vm.disk :disk, size: "1GB", name: "disk2"
    client.vm.disk :disk, size: "1GB", name: "disk3"
   # client.vm.disk :disk, size: "1GB", name: "disk4"
   # client.vm.disk :disk, size: "1GB", name: "disk5"
   # client.vm.disk :disk, size: "1GB", name: "disk6"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

#config.trigger.before :destroy do
#  info "removing disks......................"
#  run "rm -fv *.vdi"
#end

end

