Vagrant.configure("2") do |config|
  
    config.vm.box = 'centos/8.4'
    config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'
    config.vm.box_download_checksum = 'dfe4a34e59eb3056a6fe67625454c3607cbc52ae941aeba0498c29ee7cb9ac22'
    config.vm.box_download_checksum_type = 'sha256'
  
  config.vm.define "server" do |server|
  
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  
    server.vm.disk :disk, size: "1GB", name: "disk1"
    server.vm.disk :disk, size: "1GB", name: "disk2"
    server.vm.disk :disk, size: "1GB", name: "disk3"
    server.vm.host_name = 'server'
    server.vm.network :private_network, ip: "10.0.3.15"
  
    server.vm.provision "shell", inline: <<-SHELL
               echo '---------------------installing necessary packages--------------------------'
               yum install -y redhat-lsb-core wget rpmdevtools rpm-build createrepo yum-utils
           SHELL
  
#    server.vm.provision "shell",
 #     name: "Setup zfs",
  #    path: "setup_zfs.sh"
    end
end
