# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:server => {
        :box_name => "centos/7",
        :hostname => "server",
        :os_type => "centos",
        :ssh_port => 2200,
        :ram => 1024,
        :cpu => 2,
        :net => [
          {ip: '10.0.0.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net0"},
          {ip: '172.16.1.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "netps"},
                ]
        }       ,
:client => {
        :box_name => "centos/7",
        :hostname => "client",
        :os_type => "centos",
        :ssh_port => 2201,
        :ram => 1024,
        :cpu => 2,
        :net => [
          {ip: '10.0.0.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net0"},
          {ip: '172.16.2.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "netsp"},
                ]
        }       ,
:pc1=> {
        :box_name => "centos/7",
        :hostname => "pc1",
        :os_type => "centos",
        :ssh_port => 2202,
        :ram => 1024,
        :cpu => 2,
        :net => [
          {ip: '172.16.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "netps"},
                ]
        }       ,
:pc2=> {
        :box_name => "centos/7",
        :hostname => "pc2",
        :os_type => "centos",
        :ssh_port => 2203,
        :ram => 1024,
        :cpu => 2,
        :net => [
          {ip: '172.16.2.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "netsp"},
                ]
        }       ,


}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.hostname = boxconfig[:hostname]
        box.vbguest.auto_update = false
        box.ssh.keys_only = true
        box.ssh.insert_key = true
        box.vm.network :forwarded_port,host:boxconfig[:ssh_port], guest:22,id:'ssh'
        box.vm.provider "virtualbox" do |vb_machine_settings|
                vb_machine_settings.customize ["modifyvm", :id, "--memory", boxconfig[:ram]]
                vb_machine_settings.customize ["modifyvm", :id, "--cpus", boxconfig[:cpu]]
            end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

#               
        case boxconfig[:os_type]

        when "centos"
        box.vm.provision "shell", inline: <<-SHELL
                ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
                cp /root/.ssh/id_rsa /home/vagrant/id.rsa
        SHELL
#        box.vm.provision :shell, :inline => "mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh"
        box.vm.provision :shell, :inline => "sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
        box.vm.provision :shell, :inline => "systemctl enable sshd"
        box.vm.provision :shell, :inline => "systemctl restart sshd"
        box.vm.provision "shell", inline: <<-SHELL
                 yum update
                 yum install epel-release centos-release-scl -y
        SHELL


        when "ubuntu"
        box.vm.provision "shell", inline: <<-SHELL
                ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
                curl -s https://deb.frrouting.org/frr/keys.asc | sudo apt-key add -
                echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable > /etc/apt/sources.list.d/frr.list
                apt update -y
                apt install net-tools sshpass -y
        SHELL

        end
        #box.vm.provision "ansible" do |ansible|
        #  ansible.playbook = "main.yaml"
        #end
        case boxname.to_s

        when "server" 
            box.vm.provision "ansible", run: "always" do |ansible|
            ansible.playbook = "setup_server.yaml"
          end
        when "client" 
            box.vm.provision "ansible", run: "always" do |ansible|
            ansible.playbook = "setup_client.yaml"
          end
        when "pc1" 
            box.vm.provision "ansible", run: "always" do |ansible|
            ansible.playbook = "setup_pc1.yaml"
          end
        when "pc2" 
            box.vm.provision "ansible", run: "always" do |ansible|
            ansible.playbook = "setup_pc2.yaml"
          end

        end
        end        

      end

  end
  
  
