---
# tasks file for copy_keys_to_server
- name: Copy key files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/openvpn/{{item}}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "1.1.1.1.crt"
    - '1.1.1.1.key'
    - 'ca.crt'
    - 'dh2048.pem'


