# -*- mode: ruby -*-
# vim: set ft=ruby :
home_vb = ENV['VBOX_storage']

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.4',
	:disks => {
		:sata1 => {
			:dfile => home_vb + '/VirtualBox VMs/sata1.vdi',
			:size => 1024,
			:port => 1
		},
		:sata2 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata2.vdi',
                        :size => 2048, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata3.vdi',
                        :size => 2048,
                        :port => 3
                },
                :sata4 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata4.vdi',
                        :size => 4096, # Megabytes
                        :port => 4
                },
                :sata5 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata5.vdi',
                        :size => 4096, # Megabytes
                        :port => 5
                },
                :sata6 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata6.vdi',
                        :size => 2048, # Megabytes
                        :port => 6
                },
                :sata7 => {
                        :dfile => home_vb + '/VirtualBox VMs/sata7.vdi',
                        :size => 2048, # Megabytes
                        :port => 7
                }






	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
              yum install -y dosfstools lvm2
              export device='/dev/sdb'
              echo 'creating boot partitions on boot drive sdb'
              sgdisk -n 0:0:+512M -t 0:ef00 -c 0:efi-boot $device
              mkfs.vfat -F32 /dev/sdb1
              sgdisk -e $device #backup
              echo '---------------creating raid5------------------------'
              lsblk
              echo '--------------------zeroing superblock----------------'
              mdadm --zero-superblock --force /dev/sd{c,d,e,f,g}
              echo '----------------creating raid5------------------------'
              yes y | mdadm --create --verbose --metadata=1.2 --force /dev/md0 -l 5 -n 5 /dev/sd{c,d,e,f,g}
              cat /proc/mdstat
              mkdir -p /etc/mdadm
              touch /etc/mdadm/mdadm.conf
              echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
              yes | mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
              mkdir /raid
              mkdir -p /raid/part{1,2,3,4,5,6}
              chown -R vagrant /raid
              #echo '---------------creating parting 5 paritions for LVM-------------------------------'
              export device='/dev/md0'
              for i in {1..5}; do echo "partioning ${i}'th disk......"; sgdisk -n ${i}:0:+512M $device ; done
              for i in {1..5}; do echo "choosing type LVM for ${i}'th disk......"; sgdisk -t ${i}:8e00 $device ; done
              for i in {1..5}; do echo "labeling ${i}'th disk......"; sgdisk -c ${i}:lvm-partition_${i} $device ; done
              #for i in {1..5}; do echo "$making ext4 on {i}'th disk"; mkfs.ext4 /dev/md0/p${i} ; done
              echo '---------------partioning complete-----------------------'
              echo '-------------assembling LVM from created partitions.....----------------------'
              pvcreate /dev/md0p{1..5}
              pvscan
              vgcreate raid_5_test /dev/md0p{1..5}
              vgdisplay
              echo '--------creating LVM logical volumes---------------'
              export name_part1='some_part1'
              export name_part2='some_part2'
              lvcreate -L 1G -n $name_part1 raid_5_test
              mkfs.ext4 /dev/raid_5_test/some_part1
              lvcreate -L 1G -n $name_part2 raid_5_test
              mkfs.ext4 /dev/raid_5_test/some_part2
              echo '--------adding fstab entities--------------------'
              sed -i -e '$a\/dev/raid_5_test/some_part1     /raid/part1     ext4    defaults        0       2' /etc/fstab
              sed -i -e '$a\/dev/raid_5_test/some_part2     /raid/part2     ext4    defaults        0       2' /etc/fstab
              echo '-------------mounting lvm volumes on /raid-----------------------'
              mount -a
              #mount /dev/raid_5_test/some_part1 /raid/part1
              #mount /dev/raid_5_test/some_part2 /raid/part2
              cd /raid/part1 
              fallocate -l 1M somefile.data
              mdadm --detail /dev/md0 | grep UUID
              

  	  SHELL
         box.vm.provision :shell, :inline => "cat /proc/mdstat", run: "always"
         box.vm.provision :shell, :inline => "mdadm --detail /dev/md0", run: "always"
         box.vm.provision "shell",run: "always", inline: <<-SHELL
              echo '---------------xxxxxxxxxxxxxxxxxxxxxx--------------------------------'
              vgs
              pvs
              mount | grep raid
  	  SHELL

      end
  end
end
