# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetrouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :box_version => "2004.01",
        :hostname => "inetrouter",
        :ssh_port => 2001,
        :ram => 1024,
        :cpu => 2,
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralrouter => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :hostname => "centralrouter",
        :ssh_port => 2020,
        :ram => 1024,
        :cpu => 2,
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "directors"},
                   {ip: '192.168.0.32', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "office-hw-1"},
                   {ip: '192.168.0.64', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office-hw-2"},
                   {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office2router"},
                ]
  },
  
  :centralserver => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :hostname => "centralserver",
        :ssh_port => 2021,
        :ram => 1024,
        :cpu => 2,
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "directors"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :office2router => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :hostname => "office2router",
        :ram => 1024,
        :cpu => 2,
        :net => [
                   {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2router"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev"},
                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test-servers"},
                   {ip: '192.168.1.192', adapter: 5, netmask: "255.255.255.193", virtualbox__intnet: "office-hardware"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.hostname = boxconfig[:hostname]
        box.vbguest.auto_update = false
        box.ssh.keys_only = true
        box.ssh.insert_key = true
#        box.vm.network :forwarded_port,host:boxconfig[:ssh_port], guest:22,id:'ssh'
        box.vm.provider "virtualbox" do |vb_machine_settings|
                vb_machine_settings.customize ["modifyvm", :id, "--memory", boxconfig[:ram]]
                vb_machine_settings.customize ["modifyvm", :id, "--cpus", boxconfig[:cpu]]
            end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

#               
        
        box.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        box.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
        box.vm.provision :shell, :inline => "systemctl enable sshd"
        box.vm.provision :shell, :inline => "systemctl start sshd"
        box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        box.vm.provision "shell", inline: <<-SHELL
                 yum update
                 yum install epel-release centos-release-scl -y
#                yum install -y rh-python38 which
#                 yum install -y python3
 #                rm -f /usr/bin/python
 #                ln -s /usr/bin/python3 /usr/bin/python
#                scl enable rh-python38 bash
#                 rm -f /bin/python
#                 ln -s /bin/python3 /bin/python
#                 p_version=$(python -V)
 #                echo "------------$p_version has been installed!-------------"
        SHELL
        

#        box.vm.provision :shell, :inline => "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*"
 #       box.vm.provision :shell, :inline => "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*"
  #      box.vm.provision :shell, :inline => "dnf install centos-release-stream -y"
    
        box.vm.provision "ansible", run: "always" do |ansible|
          ansible.playbook = "vm_config.yml"
        end


        case boxname.to_s
        when "inetrouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip r add 192.168.0.0/28 via 192.168.255.2 # director net routing
            SHELL
        when "centralrouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r del default
            ip route add 0.0.0.0/0 via 192.168.255.1
            systemctl restart network
            SHELL
        when "centralserver"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r del default
            ip route add 0.0.0.0/0 via 192.168.0.1
            systemctl restart network
            SHELL
        when "office2router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip r del default
            ip route add 0.0.0.0/0 via 192.168.255.5
            systemctl restart network
            SHELL
 
        end
        
        

      end

  end
  
  
end
