---
- name: routers_soft
  hosts: all 
  gather_facts: true
  become: true
  vars:
    test_version: 1
    installed_soft: ['git','mc','iproute','tcpdump','net-tools']

  tasks:
  - name: installing soft
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: present
    loop: "{{ installed_soft  }}"
  - name: installing soft main
    ansible.builtin.yum:
      name: net-tools
      state: present
        #    when: ansible_hostname == 'centralrouter'


  handlers:
    - name: restart_crond
      service:
        name=crond
        state=restarted
    - name: restart_send_mail
      service:
        name=sendmail
        state=restarted

- name: inet_routers
  hosts: centralrouter  
  gather_facts: true
  become: true
  vars:
    test_version: 1
  tasks:
  - name: printfacts
    ansible.builtin.debug:
      msg: "{{ ansible_default_ipv4['macaddress'] }}"
