---
- name: routers_soft
  hosts: all 
  gather_facts: true
  become: true
  vars:
    test_version: 1
    installed_soft: ['git','mc','iproute','tcpdump','net-tools']

  tasks:
  - name: installing soft
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: present
    loop: "{{ installed_soft  }}"
  - name: installing soft main
    ansible.builtin.yum:
      name: net-tools
      state: present
  - name: disable default route
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centrarouter") or
          (ansible_hostname == "centralserver") or
          (ansible_hostname == "office1router")
      #- name: set default route office1router
      #ansible.builtin.lineinline:
      #dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      #line: GATEWAY=192.168.255.9
      #when: (ansible_hostname == "office1router")
  - name: set default gateway centralrouter
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.255.1
    when: (ansible_hostname == "centrarouter")
  #--------------------------------------------#
  - name: patching routes inetrouter
    ansible.builtin.template:
      src: ./settings/route_template_centos.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      mode: 744
    when: (ansible_hostname == "inetrouter")
    notify: restart_network
  - name: patching routes centralrouter
    ansible.builtin.template:
      src: ./settings/route_template_centos.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      mode: 744
    when: (ansible_hostname == "centralrouter")
    notify: restart_network



  handlers:
    - name: restart_network
      service:
        name=network
        state=restarted
    - name: restart_send_mail
      service:
        name=sendmail
        state=restarted

- name: inet_routers
  hosts: centralrouter  
  gather_facts: true
  become: true
  vars:
    test_version: 1
  tasks:
  - name: printfacts
    ansible.builtin.debug:
      msg: "{{ ansible_default_ipv4['macaddress'] }}"
