---
- name: routers_soft
  hosts: all 
  gather_facts: true
  become: true
  vars:
    test_version: 1
    installed_soft: ['git','mc','iproute','tcpdump','net-tools','traceroute']
    installed_soft_ubuntu: ['git','mc','tcpdump','net-tools','traceroute']
    desired_interface_name: ""

  tasks:
  - name: setting forwarding enable centos
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: (ansible_hostname == "inetrouter") or
          (ansible_hostname == "centralrouter") or
          (ansible_hostname == "centralserver")
  - name: setting forwarding enable ubuntu & debian
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
    when: (ansible_hostname == "office1router") or
          (ansible_hostname == "office2router") or
          (ansible_hostname == "office1server") or
          (ansible_hostname == "office2server")
  - name: parse default interfaces
    set_fact:
      desired_interface_name="{{ item }}"
    when: hostvars[inventory_hostname]['ansible_{{item}}']['ipv4']['address'] == "{{ ip_only }}"
    with_items:
      - "{{ ansible_interfaces }}"
  - name: print default interface
    debug:
      var: desired_interface_name

  - name: installing soft centos
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: present
    loop: "{{ installed_soft  }}"
    when: (os_type == "centos")
  - name: installing soft ubuntu&debian
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: present
    loop: "{{ installed_soft_ubuntu  }}"
    when: (os_type == "ubuntu") or (os_type == "debian")
  - name: disable default route eth0
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
      state: present
    when: (ansible_hostname == "centralrouter") or
          (ansible_hostname == "centralserver")
  - name: set defroute eth1
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: DEFROUTE=yes
      state: present
    when: (ansible_hostname == "centralrouter") or
          (ansible_hostname == "centralserver")
  - name: set default gateway centralrouter
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY={{ gateway_def }}
      state: present
    when: (ansible_hostname == "centralrouter") or
          (ansible_hostname == "centralserver")
    notify: restart_network
  #--------------------------------------------#
  - name: patching gaweway ubuntu office1
    ansible.builtin.template:
      src: ./settings/interfaces_ubuntu_office1.j2
      dest: /etc/network/interfaces
      mode: 744
    when: (ansible_hostname == "office1router") or
          (ansible_hostname == "office1server")
  - name: patching gaweway debian office2
    ansible.builtin.template:
      src: ./settings/interfaces_debian_office2.j2
      dest: /etc/network/interfaces
      mode: 744
    when: (ansible_hostname == "office2router") or
          (ansible_hostname == "office2server")
  - name: insert route office1router
    ansible.builtin.blockinfile:
      dest: /etc/netplan/50-vagrant.yaml
      insertafter: "{{ def_ip }}"
      block: |6
                  routes:
                    - to: 0.0.0.0/0
                      via: {{ gateway_def }}
    when: (ansible_hostname == "office1router") or
          (ansible_hostname == "office1server")
    notify: restart_network_ubuntu

  - name: patching routes inetrouter
    ansible.builtin.template:
      src: ./settings/route_template_centos.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      mode: 744
    when: (ansible_hostname == "inetrouter")
    notify: restart_network
  - name: restarting network inetrouter
    ansible.builtin.command: systemctl restart network
    when: (ansible_hostname == "inetrouter") or
          (ansible_hostname == "centralserver")
  - name: patching routes centralrouter
    ansible.builtin.template:
      src: ./settings/route_template_centos.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      mode: 744
    when: (ansible_hostname == "centralrouter")
    notify: restart_network
      #- name: ubuntu routing office1
      #ansible.builtin.template:
      #src: ./settings/interfaces_ubuntu_office1.j2
      #dest: /etc/network/interfaces
      #mode: 744
      #when: (ansible_hostname == "office1router") or
      #    (ansible_hostname == "office2router")
  - name: apply netplan
    ansible.builtin.command: netplan apply
    when: (ansible_hostname == "office1router") or
          (ansible_hostname == "office1server")
    notify: restart_network_ubuntu

  handlers:
    - name: restart_network
      service:
        name=network
        state=restarted
    - name: restart_send_mail
      service:
        name=sendmail
        state=restarted
    - name: restart_network_ubuntu
      service:
        name=systemd-networkd
        state=restarted
    - name: restart_network_debian
      service:
        name=networking
        state=restarted


- name: inet_routers
  hosts: centralrouter  
  gather_facts: true
  become: true
  vars:
    test_version: 1
      #  tasks:
      #- name: printfacts
      #ansible.builtin.debug:
      #msg: "{{ ansible_default_ipv4['macaddress'] }}"
