---
# tasks file for copy_keys
- name: copy keys for server
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: ./tmp/server/
    flat: yes
  loop: 
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/ca.crt"
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/issued/1.1.1.1.crt"
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/private/1.1.1.1.key"
    - "/etc/openvpn/dh2048.pem"
