version: '3.7'

services:
  alpine_nginx_hw:
    build: . # or keros1n/alpine_nginx_my
    image: alpine_nginx_80:latest
    tty: true
    environment:
      test_env: "666"
    ports:
      - 8081:80
        #command: '/bin/sh -c "echo $$test_env"'
        #command: bash -c "
        #service nginx status
        #"
        #    command: nginx -t

