---
# tasks file for setup_client
- name: copy client conf
  ansible.builtin.copy:
    src: client1.ovpn
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: '0644'
- name: create files for logging 3
  ansible.builtin.file:
    path: /var/log/openvpn/
    owner: root
    group: root
    state: directory
- name: create files for logging
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn-status.log
    owner: root
    group: root
    mode: '0644'
    state: touch
- name: create files for logging 2
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn-client.log
    owner: root
    group: root
    mode: '0644'
    state: touch
- name: start service openvpn
  ansible.builtin.systemd:
    name: openvpn@client
    enabled: yes
    state: started


