# -*- mode: ruby -*-
# vi: set ft=ruby :
#
home_vb = ENV['VBOX_storage']
ENV['GIT_DISCOVERY_ACROSS_FILESYSTEM'] = '1'
#host_ip = '192.168.1.66'

MACHINES = [
#  :centos_8_vagrant => {
    {
	:box_name => "centos/8",
        :box_version => "2011.0",
        :hostname => "main-server",
        :ram => 1024,
        :cpu => 2,
	#:disks => {
	#	:sata1 => {
	#		:dfile => './sata1.vdi',
	#		:size => 1000,
	#		:port => 1
	#	},
	#	:sata2 => {
	#		:dfile => './sata2.vdi',
	#		:size => 1000, # Megabytes
	#		:port => 2
	#	}
        #
	#},
	:ip => "192.168.1.65",
	:port_nginx => "8082",
        :ssh_port => '4568'
		
  },    {
	:box_name => "centos/8",
        :box_version => "2011.0",
        :hostname => "reserved-server",
        :ram => 1024,
        :cpu => 1,
	:ip => "192.168.1.64",
	:port_nginx => "8083",
        :ssh_port => '4569'
		
  },

]

Vagrant.configure(2) do |config|
  config.vagrant.plugins = "vagrant-vbguest"
    MACHINES.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box_name]
            node.vm.box_version = machine[:box_version]
            node.vm.hostname = machine[:hostname]
            node.vbguest.auto_update = false
            node.ssh.keys_only = true
            node.ssh.insert_key = true
            node.vm.network :private_network, :ip => machine[:ip]
            node.vm.network :forwarded_port,host:machine[:ssh_port], guest:22,id:'ssh'
            node.vm.provider "virtualbox" do |vb_machine_settings|
                vb_machine_settings.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb_machine_settings.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
            end
        end
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
    config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provision :shell, :inline => "yum install python36 -y"
    config.vm.provision :shell, :inline => "echo -----------------shh keys copied!-----------------------"
#
    end

end


