all:
  hosts:
      inetrouter:
  children:
    testnet:
      hosts:
        centos8machine1:
        centos8machine2:
        centos8machine3:
  vars:
    ansible_user: vagrant
    ansible_host: 127.0.0.1
    ansible_ssh_password: "vagrant"
    ansible_ssh_pass: "vagrant"
    ansible_ssh_private_key: '~/.ssh/id_rsa' 
