# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'open3'
require 'fileutils'

Vagrant.configure("2") do |config|

config.vm.define "server" do |server|
  config.vm.box = 'centos/8.4'
  config.vm.box_url = 'http://cloud.centos.org/centos/8/vagrant/x86_64/images/CentOS-8-Vagrant-8.4.2105-20210603.0.x86_64.vagrant-virtualbox.box'

  server.vm.host_name = 'server'
  server.vm.network :private_network,:type => 'dhcp', :name => 'vboxnet0', :adapter => 2, ip: "10.0.0.41"

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.provision "shell", inline: <<-SHELL
              echo '---------------xxxxxxxxxxxxxxxxxxxxxx--------------------------------'
              yum install nfs-utils -y
              echo '-------------enabling firewall----------------------'
              yum -y install firewalld
              systemctl start firewalld
              firewall-cmd --add-service={nfs,nfs3,rpc-bind,mountd} --permanent
              firewall-cmd --reload
              echo 'used ports:................'
              for s in `firewall-cmd --list-services`; do firewall-cmd --permanent --service "$s" --get-ports; done;
              echo 'creating nfs infrastructure.........'
              systemctl restart rpc-statd.service rpcbind.service rpcbind.socket
              mkdir /home/vagrant/test_share
              systemctl restart nfs-server.service
              touch /home/vagrant/test_share/file_i_cant_modify
              mkdir /home/vagrant/test_share/upload 
              mkdir /home/vagrant/test_just_rw
              chmod o+rw /home/vagrant/test_just_rw 
              chown -R nobody:nobody /home/vagrant/test_share/upload
              setsebool -P nfs_export_all_rw 1
              chmod 0777 /home/vagrant/test_share/upload
              nfsconf --set nfsd vers4.2
              nfsconf --unset nfsd vers4.2
              #nfsconf --unset nfsd vers3
              touch /home/vagrant/test_share/upload/file_i_CAN_modify
              echo '/home/vagrant/test_share *(ro,sync,root_squash,fsid=2)' >> /etc/exports
              echo '/home/vagrant/test_share/upload *(rw,sync,root_squash,fsid=1)' >> /etc/exports
              echo '/home/vagrant/test_just_rw *(rw,sync,root_squash,fsid=3)' >> /etc/exports
              exportfs -avf
          SHELL

  server.vm.provision "shell",run:'always', inline: <<-SHELL
            echo 'restarting nfs server service'
            systemctl enable nfs-server.service
            systemctl start nfs-server.service
            exportfs -avr
          SHELL
  server.vm.provision "shell",
    name: "configuration",
    path: "init.sh"
  end


  config.vm.define "client" do |client|
    client.vm.box = 'centos/8.4'
    client.vm.host_name = 'client'
    client.vm.network :private_network,:type => 'dhcp', :name => 'vboxnet0', :adapter => 2, ip: "10.0.0.40"
    client.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    client.vm.provision "shell", inline: <<-SHELL
              echo '---------------xxxxxxxxxxxxxxxxxxxxxx--------------------------------'
              yum install nfs-utils -y
              yum install krb5-workstation krb5-libs -y
              mkdir /mnt/nfs_share
              mkdir /mnt/just_rw
              mkdir /mnt/upload
              systemctl enable nfs-server.service
              systemctl start nfs-server.service
              #echo '10.0.0.6:/home/vagrant/test_share       nfs     rw,vers=3,_netdev,noauto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14  0       0' >> /etc/fstab
            echo '10.0.0.6:/home/vagrant/test_share       /mnt/nfs_share  nfs4    rw,_netdev,vers=4.2,proto=tcp,auto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14      0       0' >> /etc/fstab
            echo '10.0.0.6:/home/vagrant/test_share/upload      /mnt/upload  nfs4    rw,_netdev,vers=4.2,proto=tcp,auto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14    0       0' >> /etc/fstab
              echo '10.0.0.6:/home/vagrant/test2      /mnt/just_rw  nfs4    rw,_netdev,vers=4.2,proto=tcp,auto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14    0       0' >> /etc/fstab
              SHELL
    client.vm.provision "shell",run:"always",inline: <<-SHELL
            systemctl enable nfs-client.target 
            systemctl start nfs-client.target 
            systemctl enable nfs-server.service
            systemctl start nfs-server.service 
          SHELL

    end
  end

  config.vm.define "serverv3" do |servernfs|
    servernfs.vm.box = 'centos/7.8'
    servernfs.vm.box_url = 'http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box'
    servernfs.vm.host_name = 'nfsv3'
    servernfs.vm.network :private_network,:type => 'dhcp', :name => 'vboxnet0', :adapter => 2,  ip: "10.0.0.42"
    servernfs.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    servernfs.vm.provision "shell", inline: <<-SHELL
              echo '---------------xxxxxxxxxxxxxxxxxxxxxx--------------------------------'
              yum install nfs-utils -y
              systemctl start nfs
              systemctl status nfs
              systemctl restart nfs-server.service
              mkdir /mnt/share_from_server
              echo '10.0.0.6:/home/vagrant/test_share       nfs     rw,vers=3,_netdev,noauto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14  0       0' >> /etc/fstab
#    10.0.0.6:/      /mnt/nfs_share  nfs4    rw,_netdev,vers=4.2,proto=tcp,noauto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14    0       0
#10.0.0.6:/upload      /mnt/upload  nfs4    rw,_netdev,vers=4.2,proto=tcp,noauto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14    0       0      
    SHELL

  end

end

