---
# tasks file for copy_keys
- name: copy rs keys
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: ./tmp/client/
    flat: yes
  loop: 
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/ca.crt"
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/issued/client1.crt"
    - "/home/vagrant/openvpn_easy_rsa/easyrsa3/pki/private/client1.key"
    - "/etc/openvpn/dh2048.pem"
