server_hosts:
  hosts:
    server:
      ansible_port: 2200
      ansible_ssh_private_key_file: ".vagrant/machines/server/virtualbox/private_key"
  vars:
    host_group: "servers"
clients:
  hosts:
    client:
      ansible_port: 2201
      ansible_ssh_private_key_file: ".vagrant/machines/client/virtualbox/private_key"
  vars:
    host_group: "clients"
pcs:
  hosts:
    pc1:
      ansible_port: 2202
      ansible_ssh_private_key_file: ".vagrant/machines/pc1/virtualbox/private_key"
    pc2:
      ansible_port: 2203
      ansible_ssh_private_key_file: ".vagrant/machines/pc2/virtualbox/private_key"
    #  children:
    #test_machine:
    # test_machine:
all:
  vars:
      commontoall: thisvar
      anothercommontoall: thisvar
      ansible_user: vagrant
      ansible_host: 127.0.0.1
      ansible_ssh_password: "vagrant"
      ansible_ssh_pass: "vagrant"
      ansible_ssh_private_key: '~/.ssh/id_rsa' 
      ansible_host_key_checking: false
      ansible_ssh_path_main0: "./vagrant/machines/"
      ansible_ssh_path_main1: "/virtualbox/private_key"


