---
# tasks file for setup_server_openvpn
- name: copy server conf
  ansible.builtin.copy:
    src: server.ovpn
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: '0644'
- name: create files for logging 1
  ansible.builtin.file:
    path: /var/log/openvpn/
    owner: root
    group: root
    state: directory
- name: create files for logging
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn-status.log
    owner: root
    group: root
    mode: '0644'
    state: touch
- name: create files for logging 2
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn.log
    owner: root
    group: root
    mode: '0644'
    state: touch
- name: create files for client setup
  ansible.builtin.file:
    path: /etc/openvpn/ccd
    owner: root
    group: root
    state: directory
- name: copy client1 conf
  ansible.builtin.copy:
    src: client1.conf
    dest: /etc/openvpn/ccd/client1
    owner: root
    group: root
    mode: '0644'
- name: start service openvpn
  ansible.builtin.systemd:
    name: openvpn@server
    enabled: yes
    state: started

